package api

import (
	"embed"
	"encoding/json"
	"fmt"
	"strings"

	"isms.sh/internal/isms/db"
)

// regions.json is generated by `node web/scripts/i18nRegionCodes.mjs --json`,
// which also generates the picker's code list and the migration that converted
// existing rows — so the codes this file knows about are exactly the codes the
// picker offers and the migration produced. `web/test/regionCodes.test.js`
// asserts the committed file still matches the generator (the check lives on the
// JS side because that is where the generator can be run).
//
// It is embedded rather than read from disk because it is program text, not
// deployable content: CLAUDE.md's "templates from disk" rule governs standard
// content under ISMS_TEMPLATE_PATH, which must stay swappable without a rebuild.
//
//go:embed regions.json
var regionData embed.FS

type regionEntry struct {
	Code string `json:"code"`
	// Legacy is the English name the old picker offered and therefore what
	// `legal_requirements.jurisdiction` held before the conversion. Frozen
	// history: it exists so a search that worked before still works.
	Legacy string `json:"legacy"`
	// Label is the current English display name, as the BROWSER renders it.
	//
	// Carried in the data file rather than looked up here, and this is the
	// reason `golang.org/x/text` is not used for it: x/text ships its own CLDR
	// snapshot and does not agree with the browser's. It calls `SZ` "Swaziland"
	// and `MK` "Macedonia" where the browser says "Eswatini" and "North
	// Macedonia". Indexing x/text's answer would make a row findable under a
	// name no reader can see on screen — the same defect as resolving a code the
	// client renders verbatim.
	Label string `json:"label"`
}

// regionSearchTerms maps an offered code to the names it should be findable by.
// Sentinels are absent deliberately: `Global`/`EU`/`EEA`/`APAC` are not ISO
// 3166, they carry their own `common.region.*` translations, and `EU` in
// particular would otherwise pull in "European Union" — a name the picker never
// shows, because it and `common.region.eu` both call it "EU".
var regionSearchTerms = loadRegionSearchTerms()

func loadRegionSearchTerms() map[string][]string {
	raw, err := regionData.ReadFile("regions.json")
	if err != nil {
		panic(fmt.Sprintf("embedded regions.json unreadable: %v", err))
	}
	var parsed struct {
		Sentinels []string      `json:"sentinels"`
		Entries   []regionEntry `json:"entries"`
	}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		panic(fmt.Sprintf("embedded regions.json malformed: %v", err))
	}
	if len(parsed.Entries) == 0 {
		panic("embedded regions.json has no entries")
	}
	out := make(map[string][]string, len(parsed.Entries))
	for _, e := range parsed.Entries {
		terms := []string{e.Label}
		// The two agree for 182 of 197; the rest are spelling drift in CLDR
		// ("Czech Republic" became "Czechia", "and" became "&"). Both go in.
		if e.Legacy != e.Label {
			terms = append(terms, e.Legacy)
		}
		out[e.Code] = terms
	}
	return out
}

// legalSearchText builds the searchable blob for a legal requirement.
//
// It exists because `jurisdiction` stopped being English prose. The column used
// to hold the picker's display string ("Iceland"), and three call sites folded it
// straight into the index, so searching "Iceland" found the row. It now holds an
// ISO 3166-1 alpha-2 code, and "IS" is not a term anyone types — which would
// have made every converted row unfindable by the only name its reader has ever
// seen for it. The names go in alongside the code so both work.
//
// English specifically, not the searcher's locale. The index is one denormalised
// row per entity, written once at mutation time by whoever happened to save it,
// and read by every member of the org; there is no locale in scope at write time
// that would be right for all readers. English is the language the column held
// until this release, so indexing both the current and the pre-conversion name
// keeps every query that worked before this change working after it. Indexing
// the reader's own language means rebuilding the index per locale, which is a
// different piece of work.
//
// Three call sites shared this concatenation by copy-paste (create, update, and
// the full rebuild in api_search.go); they are collapsed here so the next change
// cannot land in two of them.
func legalSearchText(lr *db.LegalRequirement) string {
	parts := []string{lr.Identifier, lr.Title, lr.Description, lr.Jurisdiction}
	parts = append(parts, regionSearchNames(lr.Jurisdiction)...)
	return strings.ToLower(strings.Join(parts, " "))
}

// regionSearchNames returns the English names for an offered region code, or
// nothing at all for any other value — a sentinel, a legacy English name the
// migration did not convert, or free text from the CLI or an agent suggestion.
// In each of those cases the raw value is already in the blob and is the best
// term available.
//
// Gated on the offered set, NOT on "looks like two uppercase letters". That gate
// has to match `regionLabel()` in web/src/composables/useFormat.js exactly,
// because anything this resolves that the client renders verbatim makes a row
// findable under a name it never displays. A bare alpha-2 test is too wide in
// both directions: CLDR answers for codes the picker never offered, including
// pseudo-regions that are not places at all ("ZZ" is "Unknown Region", "XA" is
// "Pseudo-Accents", "EZ" is "Eurozone"), and `language.ParseRegion` is
// case-insensitive so it would resolve "is" as well as "IS".
func regionSearchNames(value string) []string {
	return regionSearchTerms[value]
}
